### ISSUE TITLE
(Linux) (Build) UI - Build fails on nodejs v18.x

### ISSUE THREAD

**Issue by Kartikeya-IYER** [ivpn/desktop-app#165]
# Bug report

## Describe your environment

* Device: Odroid HC4 (arm64 SoC)  
* OS name and version: Ubuntu 22.04 LTS  (Jammy Jellyfish)
    ```
    root@odroidhc4:~# uname -a
    Linux odroidhc4 5.10.102-meson64 #22.02.1 SMP PREEMPT Sun Feb 27 09:09:25 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
    ``` 
* IVPN app version: 3.8.7  

## Describe the problem

The UI build fails on nodejs v18.x which is the latest version available at https://github.com/nodesource/distributions (currently installs nodejs v18.2.0).

If I install nodejs v16.x, the UI builds fine.

### Steps to reproduce:

1. Install all prerequisites except nodejs
2. Install nodejs v18.x using the instructions from https://github.com/nodesource/distributions#installation-instructions for `Node.js v18.x`:
   ```
    # Using Ubuntu
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    sudo apt-get install -y nodejs
   ```
3. Update npm to the latest available:
   ```
   npm install -g npm@8.10.0
   ```
4. Build the UI (make sure to apply the arm64 fix from [this](https://github.com/ivpn/desktop-app/pull/159) merged PR):
   ```
   cd ui/References/Linux/ && ./build.sh -v 3.8.7
   ```

### Observed Results:

UI Build fails with the following messages
```
> ivpn-ui@3.8.7 electron:build
> node pre_build.js && vue-cli-service electron:build

Using style loader script: /root/IVPN_SOURCE_CODE/desktop-app/ui/src/main_style_linux.js
 INFO  Bundling render process:

⠸  Building modern bundle for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/webpack/lib/NormalModule.js:471:10)
    at /root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/webpack/lib/NormalModule.js:503:5
    at /root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/webpack/lib/NormalModule.js:358:12
    at /root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
⠼  Building modern bundle for production.../root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/loader-runner/lib/LoaderRunner.js:114
			throw e;
			^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/webpack/lib/NormalModule.js:471:10)
    at /root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/webpack/lib/NormalModule.js:503:5
    at /root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/webpack/lib/NormalModule.js:358:12
    at /root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/loader-runner/lib/LoaderRunner.js:186:6
    at context.callback (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/cache-loader/dist/index.js:240:7
    at /root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/neo-async/async.js:2830:7
    at done (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/neo-async/async.js:2865:11)
    at /root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/neo-async/async.js:2818:7
    at Array.<anonymous> (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/cache-loader/dist/index.js:229:9)
    at Storage.finished (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at callback (/root/IVPN_SOURCE_CODE/desktop-app/ui/node_modules/graceful-fs/polyfills.js:299:20)
    at FSReqCallback.oncomplete (node:fs:205:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.2.0
FAILED

```

If I install nodejs v16.x, the UI builds fine.

### Expected Results:

* What did you expect to happen?  
Either the UI build should succeed using the latest nodejs version, or the documentation needs to be changed to explicitly state that nodejs 16.x is the required version of nodejs.

### Relevant Code:

Not Applicable

**Comment by stenya** [comment]
Hi, @Kartikeya-IYER 

According to:
https://nodejs.org/en/about/releases/
```Production applications should only use Active LTS or Maintenance LTS releases.```
Currently, the Active LTS is the v16.

I am closing the ticket since there is no issue here.

**Comment by Kartikeya-IYER** [comment]
@stenya That seems reasonable. 

However, in that case - as I had said in the "Expected Results" section above - I think that the IVPN [README](https://github.com/ivpn/desktop-app#linux) Requirements section should explicitly mention that nodejs should be the LTS version (or better yet the exact npm version currently supported), because just a link to https://www.npmjs.com/get-npm would lead people to try the latest version.

**Comment by stenya** [comment]
@Kartikeya-IYER readme is updated
